// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_gamma_bounds
NumericVector get_gamma_bounds(double p0);
RcppExport SEXP _exdqlm_get_gamma_bounds(SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_gamma_bounds(p0));
    return rcpp_result_gen;
END_RCPP
}
// dexal
double dexal(double x, double p0, double mu, double sigma, double gamma, bool log_);
RcppExport SEXP _exdqlm_dexal(SEXP xSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP log_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type log_(log_SEXP);
    rcpp_result_gen = Rcpp::wrap(dexal(x, p0, mu, sigma, gamma, log_));
    return rcpp_result_gen;
END_RCPP
}
// pexal
double pexal(double q, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_pexal(SEXP qSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pexal(q, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qexal
double qexal(double prob, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_qexal(SEXP probSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qexal(prob, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rexal
NumericVector rexal(int n, double p0, double mu, double sigma, double gamma);
RcppExport SEXP _exdqlm_rexal(SEXP nSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rexal(n, p0, mu, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exdqlm_get_gamma_bounds", (DL_FUNC) &_exdqlm_get_gamma_bounds, 1},
    {"_exdqlm_dexal", (DL_FUNC) &_exdqlm_dexal, 6},
    {"_exdqlm_pexal", (DL_FUNC) &_exdqlm_pexal, 7},
    {"_exdqlm_qexal", (DL_FUNC) &_exdqlm_qexal, 7},
    {"_exdqlm_rexal", (DL_FUNC) &_exdqlm_rexal, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_exdqlm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
